### ISSUE TITLE
Base class loses declaration

### ISSUE THREAD

**Issue by Cjpbolton** [roncli/LibWowAPI#1]
Create a new VS2012 project winforms or webforms, reference the .dll. Optionally place pdb in same directory. Import roncliProductions.LibWowAPI, roncliProductions.LibWowAPI Internationalization

Try to call WowAPIData class, watch class become undeclared at runtime preventing compile.

However attaching the source code to a pre-existing solution appears to work just fine.

**Comment by roncli** [comment]
I cannot reproduce this.  See if I'm creating the solution the same way you are.  My sample project is at http://www.roncli.com/files/WindowsApplication1.zip
